FROM windriver/ubuntu1804_64
MAINTAINER Anders Wallin

USER root

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt-get update
RUN apt-get install -y moreutils bc bsdmainutils rsync lsb-release
